j = {
    'IGHJ1':
        'GCTGAATACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCAG',
    'IGHJ2': 
        'CTACTGGTACTTCGATCTCTGGGGCCGTGGCACCCTGGTCACTGTCTCCTCAG',
    'IGHJ3':
        'TGATGCTTTTGATGTCTGGGGCCAAGGGACAATGGTCACCGTCTCTTCAG',
    'IGHJ4':
        'ACTACTTTGACTACTGGGGCCAAGGAACCCTGGTCACCGTCTCCTCAG',
    'IGHJ5':
        'ACAACTGGTTCGACTCCTGGGGCCAAGGAACCCTGGTCACCGTCTCCTCAG',
    'IGHJ6':
        'ATTACTACTACTACTACGGTATGGACGTCTGGGGGCAAGGGACCACGGTCACCGTCTCCTCAG',
}

# How many nucleotides from J are upstream of CDR3
j_offset = 31
