from sldb.common.settings import DATABASE_SETTINGS

j = {
    'IGHJ1|4|5':
        'CTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCAG',
    'IGHJ2': 
        'CTACTGGTACTTCGATCTCTGGGGCCGTGGCACCCTGGTCACTGTCTCCTCAG',
    'IGHJ3':
        'TGATGCTTTTGATGTCTGGGGCCAAGGGACAATGGTCACCGTCTCTTCAG',
    'IGHJ6':
        'ATTACTACTACTACTACGGTATGGACGTCTGGGGGCAAGGGACCACGGTCACCGTCTCCTCAG',
}

# How many nucleotides from J are upstream of CDR3
j_offset = 31

v = DATABASE_SETTINGS['v_germlines']
